### ISSUE TITLE
getting error while using ui-bootstrap with 720kb.datepicker module at a time in same application.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [720kb/angular-datepicker#116]
Hi,I am getting the following error while using  ui-bootstrap with 720kb.datepicker module in same application in Angular.js

Error:

```
Error: [$compile:multidir] http://errors.angularjs.org/1.4.6/$compile/multidir?p0=datepicker&p1=&p2=da…-prev%3D%22%3Ci%20class%3D%26quot%3Bfa%20fa-arrow-circle-left%26quot%3B%3E
    at Error (native)
    at http://oditek.in/Gofasto/js/angularjs.js:6:416
    at Q (http://oditek.in/Gofasto/js/angularjs.js:69:353)
    at D (http://oditek.in/Gofasto/js/angularjs.js:62:492)
    at http://oditek.in/Gofasto/js/angularjs.js:68:182
    at http://oditek.in/Gofasto/js/angularjs.js:118:334
    at n.$eval (http://oditek.in/Gofasto/js/angularjs.js:132:452)
    at n.$digest (http://oditek.in/Gofasto/js/angularjs.js:129:463)
    at n.$apply (http://oditek.in/Gofasto/js/angularjs.js:133:236)
    at g (http://oditek.in/Gofasto/js/angularjs.js:87:376)
```
I am explaining my code below.

```
<datepicker date-format="dd-MM-y" button-prev='<i class="fa fa-arrow-circle-left"></i>' button-next='<i class="fa fa-arrow-circle-right"></i>'> 
 <input type="text" name="birthdate" class="form-control" ng-model="date" placeholder="Add date" />
</datepicker>

```
I am including both module in same application and getting this error.Please help me to resolve this error.

**Comment by 45kb** [comment]
Hi is a known problem, bootstrap-ui is using the same directive name, try switching from this:

`<datepicker>`

to this

`<div class="datepicker">`

otherwise you have to remove their directive to use this module.

**Comment by subhrajyotiw5rtc** [comment]
Thanks ,Its gave me the perfect solution.

**Comment by 45kb** [comment]
You're welcome!
