### ISSUE TITLE
hyphen parse error in datepicker

### ISSUE THREAD

**Issue by shabetya** [720kb/angular-datepicker#67]
Hi everyone. I have the next problem. My angular app began not parse "-" in all expression. Exactly in datepicker also I have parse error

Error: [$parse:ueoe] http://errors.angularjs.org/1.2.28/$parse/ueoe?p0=move(
    at Error (native)
    at http://camper.loc/bower_components/angular/angular.min.js:6:450
    at gb.peekToken (http://camper.loc/bower_components/angular/angular.min.js:170:378)
    at gb.functionCall (http://camper.loc/bower_components/angular/angular.min.js:177:231)
    at gb.primary (http://camper.loc/bower_components/angular/angular.min.js:170:73)
    at gb.unary (http://camper.loc/bower_components/angular/angular.min.js:176:73)
    at gb.multiplicative (http://camper.loc/bower_components/angular/angular.min.js:175:310)
    at gb.additive (http://camper.loc/bower_components/angular/angular.min.js:175:170)
    at gb.relational (http://camper.loc/bower_components/angular/angular.min.js:175:34)
    at gb.equality (http://camper.loc/bower_components/angular/angular.min.js:174:400) 

<pre> type="button" class="btn btn-default btn-sm pull-left" ng-click="move(-1)" tabindex="-1"</pre>

it doesn't like "-1" in ng-click move function .

Thanks for any help!

**Comment by 45kb** [comment]
@shabetya  Hi sorry for the delay, this looks like an angular related problem not a datepicker problem.
